//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="enrollee", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial class enrollee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string date_callField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string date_comingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string patronymicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string time_callField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string time_comingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string turnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cash {
            get {
                return this.cashField;
            }
            set {
                if ((object.ReferenceEquals(this.cashField, value) != true)) {
                    this.cashField = value;
                    this.RaisePropertyChanged("cash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date_call {
            get {
                return this.date_callField;
            }
            set {
                if ((object.ReferenceEquals(this.date_callField, value) != true)) {
                    this.date_callField = value;
                    this.RaisePropertyChanged("date_call");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date_coming {
            get {
                return this.date_comingField;
            }
            set {
                if ((object.ReferenceEquals(this.date_comingField, value) != true)) {
                    this.date_comingField = value;
                    this.RaisePropertyChanged("date_coming");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string patronymic {
            get {
                return this.patronymicField;
            }
            set {
                if ((object.ReferenceEquals(this.patronymicField, value) != true)) {
                    this.patronymicField = value;
                    this.RaisePropertyChanged("patronymic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string time_call {
            get {
                return this.time_callField;
            }
            set {
                if ((object.ReferenceEquals(this.time_callField, value) != true)) {
                    this.time_callField = value;
                    this.RaisePropertyChanged("time_call");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string time_coming {
            get {
                return this.time_comingField;
            }
            set {
                if ((object.ReferenceEquals(this.time_comingField, value) != true)) {
                    this.time_comingField = value;
                    this.RaisePropertyChanged("time_coming");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string turn {
            get {
                return this.turnField;
            }
            set {
                if ((object.ReferenceEquals(this.turnField, value) != true)) {
                    this.turnField = value;
                    this.RaisePropertyChanged("turn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState);
        
        string EndGetData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WpfApplication1.ServiceReference1.CompositeType GetDataUsingDataContract(WpfApplication1.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.IAsyncResult BeginGetDataUsingDataContract(WpfApplication1.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState);
        
        WpfApplication1.ServiceReference1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vivod", ReplyAction="http://tempuri.org/IService1/vivodResponse")]
        WpfApplication1.ServiceReference1.enrollee[] vivod();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/vivod", ReplyAction="http://tempuri.org/IService1/vivodResponse")]
        System.IAsyncResult Beginvivod(System.AsyncCallback callback, object asyncState);
        
        WpfApplication1.ServiceReference1.enrollee[] Endvivod(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dobav", ReplyAction="http://tempuri.org/IService1/dobavResponse")]
        bool dobav(string surname, string name, string patronymic, string date_coming, string time_coming, string date_call, string time_call, string status, string turn);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/dobav", ReplyAction="http://tempuri.org/IService1/dobavResponse")]
        System.IAsyncResult Begindobav(string surname, string name, string patronymic, string date_coming, string time_coming, string date_call, string time_call, string status, string turn, System.AsyncCallback callback, object asyncState);
        
        bool Enddobav(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/dobav1", ReplyAction="http://tempuri.org/IService1/dobav1Response")]
        bool dobav1(string Id_type_status, string Id_cash, string date_status, string tame_status);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/dobav1", ReplyAction="http://tempuri.org/IService1/dobav1Response")]
        System.IAsyncResult Begindobav1(string Id_type_status, string Id_cash, string date_status, string tame_status, System.AsyncCallback callback, object asyncState);
        
        bool Enddobav1(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getidstatus", ReplyAction="http://tempuri.org/IService1/getidstatusResponse")]
        string getidstatus(string idts, string casa, string ds, string ts);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/getidstatus", ReplyAction="http://tempuri.org/IService1/getidstatusResponse")]
        System.IAsyncResult Begingetidstatus(string idts, string casa, string ds, string ts, System.AsyncCallback callback, object asyncState);
        
        string Endgetidstatus(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/vozvr_spis", ReplyAction="http://tempuri.org/IService1/vozvr_spisResponse")]
        string[] vozvr_spis();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/vozvr_spis", ReplyAction="http://tempuri.org/IService1/vozvr_spisResponse")]
        System.IAsyncResult Beginvozvr_spis(System.AsyncCallback callback, object asyncState);
        
        string[] Endvozvr_spis(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actcash", ReplyAction="http://tempuri.org/IService1/actcashResponse")]
        bool[] actcash();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/actcash", ReplyAction="http://tempuri.org/IService1/actcashResponse")]
        System.IAsyncResult Beginactcash(System.AsyncCallback callback, object asyncState);
        
        bool[] Endactcash(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/actact", ReplyAction="http://tempuri.org/IService1/actactResponse")]
        bool actact(int number_cash, int type);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/actact", ReplyAction="http://tempuri.org/IService1/actactResponse")]
        System.IAsyncResult Beginactact(int number_cash, int type, System.AsyncCallback callback, object asyncState);
        
        bool Endactact(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/cash_off", ReplyAction="http://tempuri.org/IService1/cash_offResponse")]
        bool cash_off(int number_cash);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/cash_off", ReplyAction="http://tempuri.org/IService1/cash_offResponse")]
        System.IAsyncResult Begincash_off(int number_cash, System.AsyncCallback callback, object asyncState);
        
        bool Endcash_off(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/turn_cash", ReplyAction="http://tempuri.org/IService1/turn_cashResponse")]
        int turn_cash(int cash);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/turn_cash", ReplyAction="http://tempuri.org/IService1/turn_cashResponse")]
        System.IAsyncResult Beginturn_cash(int cash, System.AsyncCallback callback, object asyncState);
        
        int Endturn_cash(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WpfApplication1.ServiceReference1.CompositeType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WpfApplication1.ServiceReference1.CompositeType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class vivodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public vivodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WpfApplication1.ServiceReference1.enrollee[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WpfApplication1.ServiceReference1.enrollee[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class dobavCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public dobavCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class dobav1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public dobav1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getidstatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getidstatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class vozvr_spisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public vozvr_spisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class actcashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public actcashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class actactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public actactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cash_offCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public cash_offCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class turn_cashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public turn_cashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfApplication1.ServiceReference1.IService1>, WpfApplication1.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginGetDataDelegate;
        
        private EndOperationDelegate onEndGetDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataUsingDataContractDelegate;
        
        private EndOperationDelegate onEndGetDataUsingDataContractDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataUsingDataContractCompletedDelegate;
        
        private BeginOperationDelegate onBeginvivodDelegate;
        
        private EndOperationDelegate onEndvivodDelegate;
        
        private System.Threading.SendOrPostCallback onvivodCompletedDelegate;
        
        private BeginOperationDelegate onBegindobavDelegate;
        
        private EndOperationDelegate onEnddobavDelegate;
        
        private System.Threading.SendOrPostCallback ondobavCompletedDelegate;
        
        private BeginOperationDelegate onBegindobav1Delegate;
        
        private EndOperationDelegate onEnddobav1Delegate;
        
        private System.Threading.SendOrPostCallback ondobav1CompletedDelegate;
        
        private BeginOperationDelegate onBegingetidstatusDelegate;
        
        private EndOperationDelegate onEndgetidstatusDelegate;
        
        private System.Threading.SendOrPostCallback ongetidstatusCompletedDelegate;
        
        private BeginOperationDelegate onBeginvozvr_spisDelegate;
        
        private EndOperationDelegate onEndvozvr_spisDelegate;
        
        private System.Threading.SendOrPostCallback onvozvr_spisCompletedDelegate;
        
        private BeginOperationDelegate onBeginactcashDelegate;
        
        private EndOperationDelegate onEndactcashDelegate;
        
        private System.Threading.SendOrPostCallback onactcashCompletedDelegate;
        
        private BeginOperationDelegate onBeginactactDelegate;
        
        private EndOperationDelegate onEndactactDelegate;
        
        private System.Threading.SendOrPostCallback onactactCompletedDelegate;
        
        private BeginOperationDelegate onBegincash_offDelegate;
        
        private EndOperationDelegate onEndcash_offDelegate;
        
        private System.Threading.SendOrPostCallback oncash_offCompletedDelegate;
        
        private BeginOperationDelegate onBeginturn_cashDelegate;
        
        private EndOperationDelegate onEndturn_cashDelegate;
        
        private System.Threading.SendOrPostCallback onturn_cashCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;
        
        public event System.EventHandler<GetDataUsingDataContractCompletedEventArgs> GetDataUsingDataContractCompleted;
        
        public event System.EventHandler<vivodCompletedEventArgs> vivodCompleted;
        
        public event System.EventHandler<dobavCompletedEventArgs> dobavCompleted;
        
        public event System.EventHandler<dobav1CompletedEventArgs> dobav1Completed;
        
        public event System.EventHandler<getidstatusCompletedEventArgs> getidstatusCompleted;
        
        public event System.EventHandler<vozvr_spisCompletedEventArgs> vozvr_spisCompleted;
        
        public event System.EventHandler<actcashCompletedEventArgs> actcashCompleted;
        
        public event System.EventHandler<actactCompletedEventArgs> actactCompleted;
        
        public event System.EventHandler<cash_offCompletedEventArgs> cash_offCompleted;
        
        public event System.EventHandler<turn_cashCompletedEventArgs> turn_cashCompleted;
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetData(System.IAsyncResult result) {
            return base.Channel.EndGetData(result);
        }
        
        private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int value = ((int)(inValues[0]));
            return this.BeginGetData(value, callback, asyncState);
        }
        
        private object[] OnEndGetData(System.IAsyncResult result) {
            string retVal = this.EndGetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataCompleted(object state) {
            if ((this.GetDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataAsync(int value) {
            this.GetDataAsync(value, null);
        }
        
        public void GetDataAsync(int value, object userState) {
            if ((this.onBeginGetDataDelegate == null)) {
                this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
            }
            if ((this.onEndGetDataDelegate == null)) {
                this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
            }
            if ((this.onGetDataCompletedDelegate == null)) {
                this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataDelegate, new object[] {
                        value}, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
        }
        
        public WpfApplication1.ServiceReference1.CompositeType GetDataUsingDataContract(WpfApplication1.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDataUsingDataContract(WpfApplication1.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WpfApplication1.ServiceReference1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result) {
            return base.Channel.EndGetDataUsingDataContract(result);
        }
        
        private System.IAsyncResult OnBeginGetDataUsingDataContract(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WpfApplication1.ServiceReference1.CompositeType composite = ((WpfApplication1.ServiceReference1.CompositeType)(inValues[0]));
            return this.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        private object[] OnEndGetDataUsingDataContract(System.IAsyncResult result) {
            WpfApplication1.ServiceReference1.CompositeType retVal = this.EndGetDataUsingDataContract(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataUsingDataContractCompleted(object state) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataUsingDataContractAsync(WpfApplication1.ServiceReference1.CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        public void GetDataUsingDataContractAsync(WpfApplication1.ServiceReference1.CompositeType composite, object userState) {
            if ((this.onBeginGetDataUsingDataContractDelegate == null)) {
                this.onBeginGetDataUsingDataContractDelegate = new BeginOperationDelegate(this.OnBeginGetDataUsingDataContract);
            }
            if ((this.onEndGetDataUsingDataContractDelegate == null)) {
                this.onEndGetDataUsingDataContractDelegate = new EndOperationDelegate(this.OnEndGetDataUsingDataContract);
            }
            if ((this.onGetDataUsingDataContractCompletedDelegate == null)) {
                this.onGetDataUsingDataContractCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataUsingDataContractDelegate, new object[] {
                        composite}, this.onEndGetDataUsingDataContractDelegate, this.onGetDataUsingDataContractCompletedDelegate, userState);
        }
        
        public WpfApplication1.ServiceReference1.enrollee[] vivod() {
            return base.Channel.vivod();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginvivod(System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginvivod(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WpfApplication1.ServiceReference1.enrollee[] Endvivod(System.IAsyncResult result) {
            return base.Channel.Endvivod(result);
        }
        
        private System.IAsyncResult OnBeginvivod(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.Beginvivod(callback, asyncState);
        }
        
        private object[] OnEndvivod(System.IAsyncResult result) {
            WpfApplication1.ServiceReference1.enrollee[] retVal = this.Endvivod(result);
            return new object[] {
                    retVal};
        }
        
        private void OnvivodCompleted(object state) {
            if ((this.vivodCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.vivodCompleted(this, new vivodCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void vivodAsync() {
            this.vivodAsync(null);
        }
        
        public void vivodAsync(object userState) {
            if ((this.onBeginvivodDelegate == null)) {
                this.onBeginvivodDelegate = new BeginOperationDelegate(this.OnBeginvivod);
            }
            if ((this.onEndvivodDelegate == null)) {
                this.onEndvivodDelegate = new EndOperationDelegate(this.OnEndvivod);
            }
            if ((this.onvivodCompletedDelegate == null)) {
                this.onvivodCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnvivodCompleted);
            }
            base.InvokeAsync(this.onBeginvivodDelegate, null, this.onEndvivodDelegate, this.onvivodCompletedDelegate, userState);
        }
        
        public bool dobav(string surname, string name, string patronymic, string date_coming, string time_coming, string date_call, string time_call, string status, string turn) {
            return base.Channel.dobav(surname, name, patronymic, date_coming, time_coming, date_call, time_call, status, turn);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Begindobav(string surname, string name, string patronymic, string date_coming, string time_coming, string date_call, string time_call, string status, string turn, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begindobav(surname, name, patronymic, date_coming, time_coming, date_call, time_call, status, turn, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Enddobav(System.IAsyncResult result) {
            return base.Channel.Enddobav(result);
        }
        
        private System.IAsyncResult OnBegindobav(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string surname = ((string)(inValues[0]));
            string name = ((string)(inValues[1]));
            string patronymic = ((string)(inValues[2]));
            string date_coming = ((string)(inValues[3]));
            string time_coming = ((string)(inValues[4]));
            string date_call = ((string)(inValues[5]));
            string time_call = ((string)(inValues[6]));
            string status = ((string)(inValues[7]));
            string turn = ((string)(inValues[8]));
            return this.Begindobav(surname, name, patronymic, date_coming, time_coming, date_call, time_call, status, turn, callback, asyncState);
        }
        
        private object[] OnEnddobav(System.IAsyncResult result) {
            bool retVal = this.Enddobav(result);
            return new object[] {
                    retVal};
        }
        
        private void OndobavCompleted(object state) {
            if ((this.dobavCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.dobavCompleted(this, new dobavCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void dobavAsync(string surname, string name, string patronymic, string date_coming, string time_coming, string date_call, string time_call, string status, string turn) {
            this.dobavAsync(surname, name, patronymic, date_coming, time_coming, date_call, time_call, status, turn, null);
        }
        
        public void dobavAsync(string surname, string name, string patronymic, string date_coming, string time_coming, string date_call, string time_call, string status, string turn, object userState) {
            if ((this.onBegindobavDelegate == null)) {
                this.onBegindobavDelegate = new BeginOperationDelegate(this.OnBegindobav);
            }
            if ((this.onEnddobavDelegate == null)) {
                this.onEnddobavDelegate = new EndOperationDelegate(this.OnEnddobav);
            }
            if ((this.ondobavCompletedDelegate == null)) {
                this.ondobavCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndobavCompleted);
            }
            base.InvokeAsync(this.onBegindobavDelegate, new object[] {
                        surname,
                        name,
                        patronymic,
                        date_coming,
                        time_coming,
                        date_call,
                        time_call,
                        status,
                        turn}, this.onEnddobavDelegate, this.ondobavCompletedDelegate, userState);
        }
        
        public bool dobav1(string Id_type_status, string Id_cash, string date_status, string tame_status) {
            return base.Channel.dobav1(Id_type_status, Id_cash, date_status, tame_status);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Begindobav1(string Id_type_status, string Id_cash, string date_status, string tame_status, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begindobav1(Id_type_status, Id_cash, date_status, tame_status, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Enddobav1(System.IAsyncResult result) {
            return base.Channel.Enddobav1(result);
        }
        
        private System.IAsyncResult OnBegindobav1(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Id_type_status = ((string)(inValues[0]));
            string Id_cash = ((string)(inValues[1]));
            string date_status = ((string)(inValues[2]));
            string tame_status = ((string)(inValues[3]));
            return this.Begindobav1(Id_type_status, Id_cash, date_status, tame_status, callback, asyncState);
        }
        
        private object[] OnEnddobav1(System.IAsyncResult result) {
            bool retVal = this.Enddobav1(result);
            return new object[] {
                    retVal};
        }
        
        private void Ondobav1Completed(object state) {
            if ((this.dobav1Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.dobav1Completed(this, new dobav1CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void dobav1Async(string Id_type_status, string Id_cash, string date_status, string tame_status) {
            this.dobav1Async(Id_type_status, Id_cash, date_status, tame_status, null);
        }
        
        public void dobav1Async(string Id_type_status, string Id_cash, string date_status, string tame_status, object userState) {
            if ((this.onBegindobav1Delegate == null)) {
                this.onBegindobav1Delegate = new BeginOperationDelegate(this.OnBegindobav1);
            }
            if ((this.onEnddobav1Delegate == null)) {
                this.onEnddobav1Delegate = new EndOperationDelegate(this.OnEnddobav1);
            }
            if ((this.ondobav1CompletedDelegate == null)) {
                this.ondobav1CompletedDelegate = new System.Threading.SendOrPostCallback(this.Ondobav1Completed);
            }
            base.InvokeAsync(this.onBegindobav1Delegate, new object[] {
                        Id_type_status,
                        Id_cash,
                        date_status,
                        tame_status}, this.onEnddobav1Delegate, this.ondobav1CompletedDelegate, userState);
        }
        
        public string getidstatus(string idts, string casa, string ds, string ts) {
            return base.Channel.getidstatus(idts, casa, ds, ts);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Begingetidstatus(string idts, string casa, string ds, string ts, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begingetidstatus(idts, casa, ds, ts, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string Endgetidstatus(System.IAsyncResult result) {
            return base.Channel.Endgetidstatus(result);
        }
        
        private System.IAsyncResult OnBegingetidstatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idts = ((string)(inValues[0]));
            string casa = ((string)(inValues[1]));
            string ds = ((string)(inValues[2]));
            string ts = ((string)(inValues[3]));
            return this.Begingetidstatus(idts, casa, ds, ts, callback, asyncState);
        }
        
        private object[] OnEndgetidstatus(System.IAsyncResult result) {
            string retVal = this.Endgetidstatus(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetidstatusCompleted(object state) {
            if ((this.getidstatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getidstatusCompleted(this, new getidstatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getidstatusAsync(string idts, string casa, string ds, string ts) {
            this.getidstatusAsync(idts, casa, ds, ts, null);
        }
        
        public void getidstatusAsync(string idts, string casa, string ds, string ts, object userState) {
            if ((this.onBegingetidstatusDelegate == null)) {
                this.onBegingetidstatusDelegate = new BeginOperationDelegate(this.OnBegingetidstatus);
            }
            if ((this.onEndgetidstatusDelegate == null)) {
                this.onEndgetidstatusDelegate = new EndOperationDelegate(this.OnEndgetidstatus);
            }
            if ((this.ongetidstatusCompletedDelegate == null)) {
                this.ongetidstatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetidstatusCompleted);
            }
            base.InvokeAsync(this.onBegingetidstatusDelegate, new object[] {
                        idts,
                        casa,
                        ds,
                        ts}, this.onEndgetidstatusDelegate, this.ongetidstatusCompletedDelegate, userState);
        }
        
        public string[] vozvr_spis() {
            return base.Channel.vozvr_spis();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginvozvr_spis(System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginvozvr_spis(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string[] Endvozvr_spis(System.IAsyncResult result) {
            return base.Channel.Endvozvr_spis(result);
        }
        
        private System.IAsyncResult OnBeginvozvr_spis(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.Beginvozvr_spis(callback, asyncState);
        }
        
        private object[] OnEndvozvr_spis(System.IAsyncResult result) {
            string[] retVal = this.Endvozvr_spis(result);
            return new object[] {
                    retVal};
        }
        
        private void Onvozvr_spisCompleted(object state) {
            if ((this.vozvr_spisCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.vozvr_spisCompleted(this, new vozvr_spisCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void vozvr_spisAsync() {
            this.vozvr_spisAsync(null);
        }
        
        public void vozvr_spisAsync(object userState) {
            if ((this.onBeginvozvr_spisDelegate == null)) {
                this.onBeginvozvr_spisDelegate = new BeginOperationDelegate(this.OnBeginvozvr_spis);
            }
            if ((this.onEndvozvr_spisDelegate == null)) {
                this.onEndvozvr_spisDelegate = new EndOperationDelegate(this.OnEndvozvr_spis);
            }
            if ((this.onvozvr_spisCompletedDelegate == null)) {
                this.onvozvr_spisCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onvozvr_spisCompleted);
            }
            base.InvokeAsync(this.onBeginvozvr_spisDelegate, null, this.onEndvozvr_spisDelegate, this.onvozvr_spisCompletedDelegate, userState);
        }
        
        public bool[] actcash() {
            return base.Channel.actcash();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginactcash(System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginactcash(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool[] Endactcash(System.IAsyncResult result) {
            return base.Channel.Endactcash(result);
        }
        
        private System.IAsyncResult OnBeginactcash(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.Beginactcash(callback, asyncState);
        }
        
        private object[] OnEndactcash(System.IAsyncResult result) {
            bool[] retVal = this.Endactcash(result);
            return new object[] {
                    retVal};
        }
        
        private void OnactcashCompleted(object state) {
            if ((this.actcashCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.actcashCompleted(this, new actcashCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void actcashAsync() {
            this.actcashAsync(null);
        }
        
        public void actcashAsync(object userState) {
            if ((this.onBeginactcashDelegate == null)) {
                this.onBeginactcashDelegate = new BeginOperationDelegate(this.OnBeginactcash);
            }
            if ((this.onEndactcashDelegate == null)) {
                this.onEndactcashDelegate = new EndOperationDelegate(this.OnEndactcash);
            }
            if ((this.onactcashCompletedDelegate == null)) {
                this.onactcashCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnactcashCompleted);
            }
            base.InvokeAsync(this.onBeginactcashDelegate, null, this.onEndactcashDelegate, this.onactcashCompletedDelegate, userState);
        }
        
        public bool actact(int number_cash, int type) {
            return base.Channel.actact(number_cash, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginactact(int number_cash, int type, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginactact(number_cash, type, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endactact(System.IAsyncResult result) {
            return base.Channel.Endactact(result);
        }
        
        private System.IAsyncResult OnBeginactact(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int number_cash = ((int)(inValues[0]));
            int type = ((int)(inValues[1]));
            return this.Beginactact(number_cash, type, callback, asyncState);
        }
        
        private object[] OnEndactact(System.IAsyncResult result) {
            bool retVal = this.Endactact(result);
            return new object[] {
                    retVal};
        }
        
        private void OnactactCompleted(object state) {
            if ((this.actactCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.actactCompleted(this, new actactCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void actactAsync(int number_cash, int type) {
            this.actactAsync(number_cash, type, null);
        }
        
        public void actactAsync(int number_cash, int type, object userState) {
            if ((this.onBeginactactDelegate == null)) {
                this.onBeginactactDelegate = new BeginOperationDelegate(this.OnBeginactact);
            }
            if ((this.onEndactactDelegate == null)) {
                this.onEndactactDelegate = new EndOperationDelegate(this.OnEndactact);
            }
            if ((this.onactactCompletedDelegate == null)) {
                this.onactactCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnactactCompleted);
            }
            base.InvokeAsync(this.onBeginactactDelegate, new object[] {
                        number_cash,
                        type}, this.onEndactactDelegate, this.onactactCompletedDelegate, userState);
        }
        
        public bool cash_off(int number_cash) {
            return base.Channel.cash_off(number_cash);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Begincash_off(int number_cash, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begincash_off(number_cash, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endcash_off(System.IAsyncResult result) {
            return base.Channel.Endcash_off(result);
        }
        
        private System.IAsyncResult OnBegincash_off(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int number_cash = ((int)(inValues[0]));
            return this.Begincash_off(number_cash, callback, asyncState);
        }
        
        private object[] OnEndcash_off(System.IAsyncResult result) {
            bool retVal = this.Endcash_off(result);
            return new object[] {
                    retVal};
        }
        
        private void Oncash_offCompleted(object state) {
            if ((this.cash_offCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.cash_offCompleted(this, new cash_offCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void cash_offAsync(int number_cash) {
            this.cash_offAsync(number_cash, null);
        }
        
        public void cash_offAsync(int number_cash, object userState) {
            if ((this.onBegincash_offDelegate == null)) {
                this.onBegincash_offDelegate = new BeginOperationDelegate(this.OnBegincash_off);
            }
            if ((this.onEndcash_offDelegate == null)) {
                this.onEndcash_offDelegate = new EndOperationDelegate(this.OnEndcash_off);
            }
            if ((this.oncash_offCompletedDelegate == null)) {
                this.oncash_offCompletedDelegate = new System.Threading.SendOrPostCallback(this.Oncash_offCompleted);
            }
            base.InvokeAsync(this.onBegincash_offDelegate, new object[] {
                        number_cash}, this.onEndcash_offDelegate, this.oncash_offCompletedDelegate, userState);
        }
        
        public int turn_cash(int cash) {
            return base.Channel.turn_cash(cash);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginturn_cash(int cash, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginturn_cash(cash, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int Endturn_cash(System.IAsyncResult result) {
            return base.Channel.Endturn_cash(result);
        }
        
        private System.IAsyncResult OnBeginturn_cash(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int cash = ((int)(inValues[0]));
            return this.Beginturn_cash(cash, callback, asyncState);
        }
        
        private object[] OnEndturn_cash(System.IAsyncResult result) {
            int retVal = this.Endturn_cash(result);
            return new object[] {
                    retVal};
        }
        
        private void Onturn_cashCompleted(object state) {
            if ((this.turn_cashCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.turn_cashCompleted(this, new turn_cashCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void turn_cashAsync(int cash) {
            this.turn_cashAsync(cash, null);
        }
        
        public void turn_cashAsync(int cash, object userState) {
            if ((this.onBeginturn_cashDelegate == null)) {
                this.onBeginturn_cashDelegate = new BeginOperationDelegate(this.OnBeginturn_cash);
            }
            if ((this.onEndturn_cashDelegate == null)) {
                this.onEndturn_cashDelegate = new EndOperationDelegate(this.OnEndturn_cash);
            }
            if ((this.onturn_cashCompletedDelegate == null)) {
                this.onturn_cashCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onturn_cashCompleted);
            }
            base.InvokeAsync(this.onBeginturn_cashDelegate, new object[] {
                        cash}, this.onEndturn_cashDelegate, this.onturn_cashCompletedDelegate, userState);
        }
    }
}
